### ISSUE TITLE
incorrect events in scoped stores

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#30]
### 🤔 What you will need to know

JavaScript, git. Basics of [Node.js](https://nodejs.org/en/) & [npm](https://docs.npmjs.com/)
### 🐞 The Bug

We run into an issue with our "scoped store API". Hoodie comes with a store API in the browser that looks like `hoodie.store.add({foo: 'bar'})` and `hoodie.store.find('id123')`. A scoped store implicitly sets / assumes the `type` property, it looks like this:

``` js
var todoStore = hoodie.store('todo')
todoStore.add({foo: 'bar'})
// creates document {foo: 'bar', type: 'todo'}
```

The bug that we found is that our events "add", "update", "remove" and "change" are not behaving correctly on scoped stores. See the full description here: https://github.com/hoodiehq/hoodie-store-client/issues/95
### :dart: The goal

[We already prepared tests for this issue in this pull request](https://github.com/hoodiehq/hoodie-store-client/pull/96#issuecomment-220696952), you only need to enable them and find out how to make them pass :)
### :clipboard: Step by Step
- [x] **Claim this issue** @capellini
- [x] [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-store-client#testing) – make sure the setup worked by running all tests with `npm test`
- [x] **enable the prepared tests** in [hoodie-store-client/tests/specs/scoped.js](https://github.com/hoodiehq/hoodie-store-client/blob/9f3f60f65437a3c60ccaf1d3c7655a92980b1663/tests/specs/scoped.js#L688-L752) Replace `test.skip` with just `test`, remove the comments `// prepared for ...`. Safe the file, then run `npm test`. You now should see the two tests failing, as expected
- [x] **Commit** the change with `test: scoped store events`
- [x] **Start a Pull Request**. Mention `closes hoodiehq/camp#30` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [x] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by dasilvacontin** [comment]
'find out how to ~~not~~ make them pass' (?)

**Comment by gr2m** [comment]
fixed, thanks @dasilvacontin!

**Comment by vaibhavjain-git** [comment]
Hey..I want to solve this issue.
Thanks

**Comment by gr2m** [comment]
all yours, welcome @vaibhavjain-git ✨  Good luck, and let us know if you get stuck in any way, we are happy to help :)

**Comment by gr2m** [comment]
@vaibhavjain-git do you still want to look into the issue?

**Comment by gr2m** [comment]
Hey @capellini, would you like to take this one?

**Comment by capellini** [comment]
@gr2m -- sure thing, I'll take a look.

**Comment by capellini** [comment]
@gr2m -- here's the first issue that I see.  Setting up an environment as described in hoodiehq/hoodie-store-client#95, that is:
1. `npm init -y` in an empty directory
2. `npm i hoodie --save --no-optional`
3. Add the `start` command to `package.json`
4. Add a public/index.html file that has `<script src="/hoodie/client.js"></script>` in it
5. Start the app with `npm start -- --inMemory`

If I go into Chrome devtools and enter:

```
hoodie.store().add({ type: 'person', name: 'knut' })
```

I _think_ that I should expect the record to be placed into a scoped store under the scope `person`.  But right now, it looks like [lines 6 through 10 of add.js](https://github.com/hoodiehq/hoodie-store-client/blob/15152091f7b7d52aee12939dbaa589da16ff2122/lib/scoped/add.js#L6-L10) changes `type` from `person` to `undefined`.  Therefore:

```
hoodie.store('person').findAll().then(function (people) { console.log('people =', people); })
```

logs an empty list, whereas an unscoped `findAll`:

```
hoodie.store().findAll().then(function (people) { console.log('people =', people); })
```

returns the record with no type entry.

But if I change [lib/utils/add-type.js](https://github.com/hoodiehq/hoodie-store-client/blob/15152091f7b7d52aee12939dbaa589da16ff2122/lib/utils/add-type.js) so that, instead of always replacing `type`, it does something like this:

``` js
function addType (type, object) {
  if (typeof type != 'undefined' || !object.type) {
    object.type = type
  }

  return object
}
```

and then change [line 9 of lib/scoped/add.js](https://github.com/hoodiehq/hoodie-store-client/blob/15152091f7b7d52aee12939dbaa589da16ff2122/lib/scoped/add.js#L9) appropriately, then doing the above `add` does add a scoped record to under `person` scope.

Unfortunately, this doesn't solve the root cause of this problem.  What does happen, however, is now the scoped entry is properly stored and the scoped events that are triggered are consistent between the commands:

```
hoodie.store().add({ type: 'person', name: 'knut' })
```

and:

```
hoodie.store('person').add({ name: 'knut' })
```

But the scoped events that are triggered are not `add` and `change add`.  Instead, we still get the incorrect `add`, `update`, and `change update` scoped events.

What perplexes me even more is that there are tests in the repository that use `add` in its current form where `type` is not changed to `undefined`, but instead the original value is retained.

Are you seeing the same thing, or am I doing something wrong / misinterpreting something?  I'm still looking into this, but thought that I would forward this along in case you have some insight into what's going on.

**Comment by gr2m** [comment]
oh wow, thanks for the great research on this! I totally missed this line, that shouldn’t work in the first place

``` js
hoodie.store().add({ type: 'person', name: 'knut' })
```

I would argue that `hoodie.store()` should require the type property to be set. If it’s not set, it should thrown an TypeError. 

I’d suggest we do a pull request for that issue first? 

Can you point me to the tests you mentioned here? 

> What perplexes me even more is that there are tests in the repository that use add in its current form where type is not changed to undefined, but instead the original value is retained.

**Comment by capellini** [comment]
> I would argue that hoodie.store() should require the type property to be set. If it’s not set, it should thrown an TypeError.
> 
> I’d suggest we do a pull request for that issue first?

Sure thing.  I'll submit an issue and a PR for it.

Quick question -- what would be the expected behavior of a call like this?

``` js
var books = hoodie.store('books');
books.add({ title: 'book1', type: 'non-fiction', ... })
books.add({ title: 'book2', type: 'fiction', ... })
books.add({ title: 'book3', type: 'autobiography', ... })
```

In this example, we would overwrite the `type` in the records for each book to `books`.  Should we instead throw a TypeError because someone is defining a `type` which doesn't match the current scoped store `type` (i.e. the `type` property is essentially a reserved word)?

I thought that I would mention it, since `type` is a common data field for a lot of records.

> Can you point me to the tests you mentioned here?

I was reading the code wrong -- I saw `store.add(...` and thought that I was seeing `store().add(...`.  Sorry about that!

**Comment by gr2m** [comment]
Yes, I agree, we should forbid to change set the `type` property to anything other than the type passed to `hoodie.store(type)`, we should throw a type error.

I’ll make two separate issues for these on the `hoodie-client-store` module and assign them to you, ok?

**Comment by capellini** [comment]
> I’ll make two separate issues for these on the hoodie-client-store module and assign them to you, ok?

Yes, please do.  Sounds great.

**Comment by gr2m** [comment]
the issues are here, do these work for you?
- https://github.com/hoodiehq/hoodie-store-client/issues/128
- https://github.com/hoodiehq/hoodie-store-client/issues/129

**Comment by capellini** [comment]
> do these work for you?

Yes, that works.  Thanks.

**Comment by gr2m** [comment]
@capellini you are looking into this one, right? Please let me know if you have any blockers :)
